name: Docker Image CI
on:
  tag:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: VERSION=process.env.GITHUB_REF.split("/")[2].split("v")[1]
      run: docker build . --file Dockerfile --tag sharma22/hello-world:$VERSION
  
name: Node.js CI
on:
  push:
    branches: [ main ]
jobs:
  run-on: ubuntu-latest
  steps:
  - uses: action/checkout@v2
    run: npm run lint
  
