name: Docker Image
on:
  push:
    branches: [ main ]
    
jobs:
  lint: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2 
      - name: setup node
        uses: actions/setup-node@v2  
      - run: npm install && npm run lint && npm run lint-fix
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        VERSION=${GITHUB_RUN_NUMBER}
        echo VERSION=$VERSION
        docker build . --file Dockerfile --tag sharma22/hello-world:$VERSION
        docker login -u ${ process.env.DOCKER_CRED } -p ${ secrets.PASSWORD }
        docker push sharma22/hello-world:$VERSION
  build-deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
        echo "$(<kubectl.sha256) kubectl" | sha256sum --check
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        

