name: Docker Image
on:
  release:
    types: [ created ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        VERSION=process.env.GITHUB_REF.split("/")[2].split("v")[1]
        docker build . --file Dockerfile --tag sharma22/hello-world:$VERSION

