name: Docker Image
on:
  push:
    branches: [ main ]

jobs:
  lint: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2 
      - name: setup node
        uses: actions/setup-node@v2  
      - run: npm install && npm run lint && npm run lint-fix
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        VERSION=${GITHUB_RUN_NUMBER} >> $GITHUB_ENV
        echo VERSION=$VERSION
        docker build . --file Dockerfile --tag sharma22/hello-world:$VERSION
        docker login -u sharma22 -p ${{ secrets.PASSWORD }}
        docker push sharma22/hello-world:$VERSION
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2 
    - name: setup-node  
      uses: actions/setup-node@v2
    - run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && chmod +x ./kubectl && sudo mv ./kubectl /usr/local/bin/kubectl && kubectl version --client && export PATH=$PATH:/usr/local/bin/kubectl
        echo $pwd && ls
        echo kubectl version --client
        curl -L https://github.com/kubernetes/kompose/releases/download/v1.22.0/kompose-linux-amd64 -o kompose
        chmod +x kompose
        VERSION1=${GITHUB_RUN_NUMBER}
        sudo mv ./kompose /usr/local/bin/kompose
        mkdir deploy && sed -e "s/\${VERSION}/$VERSION1/" docker-compose.yml > new-docker-compose.yml && kompose -f new-docker-compose.yml convert -o deploy && cd deploy && KUBECONFIG=${{ secrets.NONPROD_KUBE_CONFIG }} /usr/local/bin/kubectl apply -f
