name: Docker Image
on:
  push:
    branches: [ main ]
    
jobs:
  lint: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2 
      - name: setup node
        uses: actions/setup-node@v2  
      - run: npm install && npm run lint && npm run lint-fix
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        VERSION=process.env.GITHUB_RUN_NUMBER
        echo VERSION=$VERSION
        docker build . --file Dockerfile --tag sharma22/hello-world:$VERSION

